apiVersion: demotest.daocloud.io/v1
kind: CronJob
metadata:
  name: cronjob-sample
spec:
  selector:
    matchLabels:
      app: gin-server
  replicas: 1
  containers:
    name: gin-server
    image: 17719317036/gin-server:v1
    imagePullPolicy: IfNotPresent
    #imagePullPolicy: Always
    resources:
      limits:
        cpu: "1"
        memory: 200Mi
    ports:
      containerPort: 9600

